sh_binary(
    name = "build_pip_pkg",
    srcs = ["build_pip_pkg.sh"],
    data = [
        "LICENSE",
        "MANIFEST.in",
        "setup.py",
        "//custom_rotate_op:custom_rotate_py",
        "//custom_fill_op:custom_fill_py",
    ],
)
